using R2Trans.Windows.Models;

namespace R2Trans.Windows.Localization;

public enum TextKey
{
    QuitR2Trans,
    Settings,
    Paste,
    TranslateSelection,
    TranslationMode,
    SettingsTitle,
    OpenAIAPIKey,
    AppLanguage,
    Hotkey,
    Model,
    AutoDetect,
    AutoDetectPair,
    ConfirmBeforeReplace,
    TranslationStyle,
    LaunchAtLogin,
    ShowTrayIcon,
    InputSource,
    AllSystemAudio,
    AudioLevel,
    MicrophoneLevel,
    SystemAudioLevel,
    KeepInterpreterOnTop,
    SourceTranscript,
    TranslatedSubtitle,
    SourceLanguage,
    TargetLanguage,
    CreateAPIKey,
    OpenAIAPIKeyHelp,
    WorkMode,
    MultilingualTranslationMode,
    SameLanguageRewriteMode,
    CurrentMode,
    ConfirmTranslationTitle,
    ConfirmTranslationMessage,
    Replace,
    CopyOnly,
    Cancel,
    Clear,
    Ok,
    Start,
    Stop,
    StyleNatural,
    StyleFormal,
    StylePolite,
    StyleGroveling,
    StyleNyang,
    NetworkError,
    OpenAIUnauthorized,
    OpenAIRateLimited,
    OpenAITemporaryFailure,
    Save,
    Close,
    SettingsError,
    PressModifierAndCharacter,
    ShortcutConflictsWithWindows,
    ShortcutNeedsMoreModifiers,
    UnsupportedKey,
    Translating,
    APIKeyMissing,
    ClipboardTextMissing,
    InvalidHotkey,
    ResponseMissing,
    AlreadyTranslating,
    MicrophonePermissionDenied,
    MicrophoneUnavailable,
    SystemAudioUnavailable,
    MicrophoneInput,
    SystemAudioInput,
    MicrophoneAndSystemAudioInput,
    LiveInterpreter,
    LiveInterpreterTitle,
    LiveInterpreterConnecting,
    LiveInterpreterListening,
    LiveInterpreterStopped,
    LiveInterpreterError,
    LiveInterpreterNoSource,
    LiveInterpreterWaitingSubtitle,
    LiveInterpreterBillingNote,
    OpenSettings,
    AppRunning,
    TrayHiddenWarning
}

public static class AppText
{
    public static AppLanguage Language { get; set; } = AppLanguage.English;

    public static string Text(TextKey key)
    {
        var table = Language switch
        {
            AppLanguage.Korean => Korean,
            AppLanguage.Japanese => Japanese,
            AppLanguage.Chinese => Chinese,
            _ => English
        };

        return table.TryGetValue(key, out var value) ? value : English[key];
    }

    public static string DisplayName(this AppLanguage language) => language switch
    {
        AppLanguage.Korean => "Korean",
        AppLanguage.Japanese => "Japanese",
        AppLanguage.Chinese => "Chinese",
        _ => "English"
    };

    public static string DisplayName(this TranslationStyle style) => Text(style switch
    {
        TranslationStyle.Formal => TextKey.StyleFormal,
        TranslationStyle.Polite => TextKey.StylePolite,
        TranslationStyle.Groveling => TextKey.StyleGroveling,
        TranslationStyle.Nyang => TextKey.StyleNyang,
        _ => TextKey.StyleNatural
    });

    public static string DisplayName(this WorkMode mode) => Text(mode switch
    {
        WorkMode.Rewrite => TextKey.SameLanguageRewriteMode,
        _ => TextKey.MultilingualTranslationMode
    });

    private static readonly Dictionary<TextKey, string> English = new()
    {
        [TextKey.QuitR2Trans] = "Quit R2Trans",
        [TextKey.Settings] = "Settings...",
        [TextKey.Paste] = "Paste",
        [TextKey.TranslateSelection] = "Translate Selection",
        [TextKey.TranslationMode] = "Translation Mode",
        [TextKey.SettingsTitle] = "R2Trans Settings",
        [TextKey.OpenAIAPIKey] = "OpenAI API Key",
        [TextKey.AppLanguage] = "App Language",
        [TextKey.Hotkey] = "Hotkey",
        [TextKey.Model] = "Model",
        [TextKey.AutoDetect] = "Auto Detect",
        [TextKey.AutoDetectPair] = "Auto Pair",
        [TextKey.ConfirmBeforeReplace] = "Confirm Before Replace",
        [TextKey.TranslationStyle] = "Translation Style",
        [TextKey.LaunchAtLogin] = "Launch at Login",
        [TextKey.ShowTrayIcon] = "Show Tray Icon",
        [TextKey.InputSource] = "Input Source",
        [TextKey.AllSystemAudio] = "All system audio",
        [TextKey.AudioLevel] = "Audio Level",
        [TextKey.MicrophoneLevel] = "Mic",
        [TextKey.SystemAudioLevel] = "System",
        [TextKey.KeepInterpreterOnTop] = "Keep on Top",
        [TextKey.SourceTranscript] = "Original",
        [TextKey.TranslatedSubtitle] = "Translation",
        [TextKey.SourceLanguage] = "Source Language",
        [TextKey.TargetLanguage] = "Target Language",
        [TextKey.CreateAPIKey] = "Create OpenAI API Key",
        [TextKey.OpenAIAPIKeyHelp] = "Create or manage an OpenAI API key",
        [TextKey.WorkMode] = "Work Mode",
        [TextKey.MultilingualTranslationMode] = "Multilingual Translation",
        [TextKey.SameLanguageRewriteMode] = "Rewrite Same Language",
        [TextKey.CurrentMode] = "Current Mode",
        [TextKey.ConfirmTranslationTitle] = "Confirm Translation",
        [TextKey.ConfirmTranslationMessage] = "Review the translated text before replacing the selection.",
        [TextKey.Replace] = "Replace",
        [TextKey.CopyOnly] = "Copy",
        [TextKey.Cancel] = "Cancel",
        [TextKey.Clear] = "Clear",
        [TextKey.Ok] = "OK",
        [TextKey.Start] = "Start",
        [TextKey.Stop] = "Stop",
        [TextKey.StyleNatural] = "Natural",
        [TextKey.StyleFormal] = "Formal",
        [TextKey.StylePolite] = "Polite",
        [TextKey.StyleGroveling] = "Overly Deferential",
        [TextKey.StyleNyang] = "Nyang style (ko-KR only)",
        [TextKey.NetworkError] = "Network connection failed. Check your internet connection and try again.",
        [TextKey.OpenAIUnauthorized] = "OpenAI rejected the API key. Check that the key is correct and active.",
        [TextKey.OpenAIRateLimited] = "OpenAI rate limit or quota was reached. Check billing, usage limits, or try again later.",
        [TextKey.OpenAITemporaryFailure] = "OpenAI is temporarily unavailable. Try again in a moment.",
        [TextKey.Save] = "Save",
        [TextKey.Close] = "Close",
        [TextKey.SettingsError] = "Settings Error",
        [TextKey.PressModifierAndCharacter] = "Press a modifier and character key",
        [TextKey.ShortcutConflictsWithWindows] = "This shortcut is commonly used by Windows or apps. Choose another shortcut.",
        [TextKey.ShortcutNeedsMoreModifiers] = "Use at least two modifiers, such as Control+Alt, for a global shortcut.",
        [TextKey.UnsupportedKey] = "Unsupported key.",
        [TextKey.Translating] = "Translating...",
        [TextKey.APIKeyMissing] = "OpenAI API key is missing. Open Settings and enter your API key.",
        [TextKey.ClipboardTextMissing] = "No selected text was found. Select text in another app, then press the R2Trans hotkey.",
        [TextKey.InvalidHotkey] = "Invalid hotkey",
        [TextKey.ResponseMissing] = "The OpenAI response did not include translated text.",
        [TextKey.AlreadyTranslating] = "A translation is already in progress.",
        [TextKey.MicrophonePermissionDenied] = "Microphone permission is required for live interpretation.",
        [TextKey.MicrophoneUnavailable] = "The microphone could not be started.",
        [TextKey.SystemAudioUnavailable] = "System audio capture could not be started. Check Windows microphone/privacy permissions and audio devices, then try again.",
        [TextKey.MicrophoneInput] = "Microphone only",
        [TextKey.SystemAudioInput] = "System audio only",
        [TextKey.MicrophoneAndSystemAudioInput] = "Microphone + system audio",
        [TextKey.LiveInterpreter] = "Live Interpreter...",
        [TextKey.LiveInterpreterTitle] = "Live Interpreter",
        [TextKey.LiveInterpreterConnecting] = "Connecting...",
        [TextKey.LiveInterpreterListening] = "Listening",
        [TextKey.LiveInterpreterStopped] = "Stopped",
        [TextKey.LiveInterpreterError] = "Live Interpreter Error",
        [TextKey.LiveInterpreterNoSource] = "Source transcript will appear here.",
        [TextKey.LiveInterpreterWaitingSubtitle] = "Translation subtitles will appear here.",
        [TextKey.LiveInterpreterBillingNote] = "Realtime translation is billed by audio duration. Free tier may not support gpt-realtime-translate.",
        [TextKey.OpenSettings] = "Open Settings",
        [TextKey.AppRunning] = "R2Trans is running",
        [TextKey.TrayHiddenWarning] = "If the tray icon is hidden, closing this window exits R2Trans."
    };

    private static readonly Dictionary<TextKey, string> Korean = new()
    {
        [TextKey.QuitR2Trans] = "R2Trans 종료",
        [TextKey.Settings] = "설정...",
        [TextKey.Paste] = "붙여넣기",
        [TextKey.TranslateSelection] = "선택 영역 번역",
        [TextKey.TranslationMode] = "번역 모드",
        [TextKey.SettingsTitle] = "R2Trans 설정",
        [TextKey.OpenAIAPIKey] = "OpenAI API 키",
        [TextKey.AppLanguage] = "앱 언어",
        [TextKey.Hotkey] = "단축키",
        [TextKey.Model] = "모델",
        [TextKey.AutoDetect] = "자동 감지",
        [TextKey.AutoDetectPair] = "자동 감지 쌍",
        [TextKey.ConfirmBeforeReplace] = "바꾸기 전 확인",
        [TextKey.TranslationStyle] = "번역 스타일",
        [TextKey.LaunchAtLogin] = "로그인 시 실행",
        [TextKey.ShowTrayIcon] = "트레이 아이콘 표시",
        [TextKey.InputSource] = "입력 소스",
        [TextKey.AllSystemAudio] = "전체 시스템 오디오",
        [TextKey.AudioLevel] = "오디오 레벨",
        [TextKey.MicrophoneLevel] = "마이크",
        [TextKey.SystemAudioLevel] = "시스템",
        [TextKey.KeepInterpreterOnTop] = "항상 위",
        [TextKey.SourceTranscript] = "원문 받아쓰기",
        [TextKey.TranslatedSubtitle] = "번역",
        [TextKey.SourceLanguage] = "원문 언어",
        [TextKey.TargetLanguage] = "타겟 언어",
        [TextKey.CreateAPIKey] = "OpenAI API 키 생성",
        [TextKey.OpenAIAPIKeyHelp] = "OpenAI API 키 생성 또는 관리",
        [TextKey.WorkMode] = "작업 모드",
        [TextKey.MultilingualTranslationMode] = "다국어 번역",
        [TextKey.SameLanguageRewriteMode] = "원문 다듬기",
        [TextKey.CurrentMode] = "현재 모드",
        [TextKey.ConfirmTranslationTitle] = "번역 확인",
        [TextKey.ConfirmTranslationMessage] = "선택 영역을 바꾸기 전에 번역 결과를 확인하세요.",
        [TextKey.Replace] = "바꾸기",
        [TextKey.CopyOnly] = "복사",
        [TextKey.Cancel] = "취소",
        [TextKey.Clear] = "지우기",
        [TextKey.Ok] = "확인",
        [TextKey.Start] = "시작",
        [TextKey.Stop] = "중지",
        [TextKey.StyleNatural] = "자연스럽게",
        [TextKey.StyleFormal] = "격식 있게",
        [TextKey.StylePolite] = "공손하게",
        [TextKey.StyleGroveling] = "비굴하게",
        [TextKey.StyleNyang] = "냥냥체(ko-KR 한정)",
        [TextKey.NetworkError] = "네트워크 연결에 실패했습니다. 인터넷 연결을 확인한 뒤 다시 시도해주세요.",
        [TextKey.OpenAIUnauthorized] = "OpenAI가 API 키를 거부했습니다. 키가 정확하고 활성 상태인지 확인해주세요.",
        [TextKey.OpenAIRateLimited] = "OpenAI 사용량 한도 또는 결제 한도에 도달했습니다. 결제/사용량 제한을 확인하거나 잠시 후 다시 시도해주세요.",
        [TextKey.OpenAITemporaryFailure] = "OpenAI 서비스가 일시적으로 응답하지 않습니다. 잠시 후 다시 시도해주세요.",
        [TextKey.Save] = "저장",
        [TextKey.Close] = "닫기",
        [TextKey.SettingsError] = "설정 오류",
        [TextKey.PressModifierAndCharacter] = "보조키와 문자 키를 함께 눌러주세요",
        [TextKey.ShortcutConflictsWithWindows] = "이 단축키는 Windows 또는 다른 앱에서 자주 사용됩니다. 다른 단축키를 선택해주세요.",
        [TextKey.ShortcutNeedsMoreModifiers] = "전역 단축키는 Control+Alt처럼 보조키를 2개 이상 함께 사용해주세요.",
        [TextKey.UnsupportedKey] = "지원하지 않는 키입니다.",
        [TextKey.Translating] = "번역 진행중",
        [TextKey.APIKeyMissing] = "OpenAI API 키가 없습니다. 설정을 열고 API 키를 입력해주세요.",
        [TextKey.ClipboardTextMissing] = "선택된 텍스트를 찾지 못했습니다. 다른 앱에서 텍스트를 선택한 뒤 R2Trans 단축키를 눌러주세요.",
        [TextKey.InvalidHotkey] = "단축키 형식이 올바르지 않습니다",
        [TextKey.ResponseMissing] = "OpenAI 응답에서 번역된 텍스트를 찾지 못했습니다.",
        [TextKey.AlreadyTranslating] = "이미 번역이 진행 중입니다.",
        [TextKey.MicrophonePermissionDenied] = "실시간 통역에는 마이크 권한이 필요합니다.",
        [TextKey.MicrophoneUnavailable] = "마이크를 시작하지 못했습니다.",
        [TextKey.SystemAudioUnavailable] = "시스템 오디오 캡처를 시작하지 못했습니다. Windows 개인정보/마이크 권한과 오디오 장치를 확인한 뒤 다시 시도해주세요.",
        [TextKey.MicrophoneInput] = "마이크만",
        [TextKey.SystemAudioInput] = "시스템 오디오만",
        [TextKey.MicrophoneAndSystemAudioInput] = "마이크 + 시스템 오디오",
        [TextKey.LiveInterpreter] = "실시간 통역...",
        [TextKey.LiveInterpreterTitle] = "실시간 통역",
        [TextKey.LiveInterpreterConnecting] = "연결 중...",
        [TextKey.LiveInterpreterListening] = "듣는 중",
        [TextKey.LiveInterpreterStopped] = "중지됨",
        [TextKey.LiveInterpreterError] = "실시간 통역 오류",
        [TextKey.LiveInterpreterNoSource] = "원문 transcript가 여기에 표시됩니다.",
        [TextKey.LiveInterpreterWaitingSubtitle] = "번역 자막이 여기에 표시됩니다.",
        [TextKey.LiveInterpreterBillingNote] = "실시간 번역은 오디오 duration 기준으로 과금됩니다. Free tier에서는 gpt-realtime-translate가 지원되지 않을 수 있습니다.",
        [TextKey.OpenSettings] = "설정 열기",
        [TextKey.AppRunning] = "R2Trans 실행 중",
        [TextKey.TrayHiddenWarning] = "트레이 아이콘을 숨기면 이 창을 닫을 때 R2Trans가 종료됩니다."
    };

    private static readonly Dictionary<TextKey, string> Japanese = new()
    {
        [TextKey.QuitR2Trans] = "R2Transを終了",
        [TextKey.Settings] = "設定...",
        [TextKey.Paste] = "ペースト",
        [TextKey.TranslateSelection] = "選択範囲を翻訳",
        [TextKey.TranslationMode] = "翻訳モード",
        [TextKey.SettingsTitle] = "R2Trans 設定",
        [TextKey.OpenAIAPIKey] = "OpenAI APIキー",
        [TextKey.AppLanguage] = "アプリの言語",
        [TextKey.Hotkey] = "ホットキー",
        [TextKey.Model] = "モデル",
        [TextKey.AutoDetect] = "自動検出",
        [TextKey.AutoDetectPair] = "自動ペア",
        [TextKey.ConfirmBeforeReplace] = "置換前に確認",
        [TextKey.TranslationStyle] = "翻訳スタイル",
        [TextKey.LaunchAtLogin] = "ログイン時に起動",
        [TextKey.ShowTrayIcon] = "トレイアイコンを表示",
        [TextKey.InputSource] = "入力ソース",
        [TextKey.AllSystemAudio] = "すべてのシステム音声",
        [TextKey.AudioLevel] = "音声レベル",
        [TextKey.MicrophoneLevel] = "マイク",
        [TextKey.SystemAudioLevel] = "システム",
        [TextKey.KeepInterpreterOnTop] = "常に手前",
        [TextKey.SourceTranscript] = "原文文字起こし",
        [TextKey.TranslatedSubtitle] = "翻訳",
        [TextKey.SourceLanguage] = "元の言語",
        [TextKey.TargetLanguage] = "翻訳先の言語",
        [TextKey.CreateAPIKey] = "OpenAI APIキーを作成",
        [TextKey.OpenAIAPIKeyHelp] = "OpenAI APIキーを作成または管理",
        [TextKey.WorkMode] = "作業モード",
        [TextKey.MultilingualTranslationMode] = "多言語翻訳",
        [TextKey.SameLanguageRewriteMode] = "同じ言語で書き直し",
        [TextKey.CurrentMode] = "現在のモード",
        [TextKey.ConfirmTranslationTitle] = "翻訳を確認",
        [TextKey.ConfirmTranslationMessage] = "選択範囲を置換する前に翻訳結果を確認してください。",
        [TextKey.Replace] = "置換",
        [TextKey.CopyOnly] = "コピー",
        [TextKey.Cancel] = "キャンセル",
        [TextKey.Clear] = "クリア",
        [TextKey.Ok] = "OK",
        [TextKey.Start] = "開始",
        [TextKey.Stop] = "停止",
        [TextKey.StyleNatural] = "自然",
        [TextKey.StyleFormal] = "フォーマル",
        [TextKey.StylePolite] = "丁寧",
        [TextKey.StyleGroveling] = "過度にへりくだる",
        [TextKey.StyleNyang] = "にゃん風(ko-KRのみ)",
        [TextKey.NetworkError] = "ネットワーク接続に失敗しました。インターネット接続を確認して、もう一度お試しください。",
        [TextKey.OpenAIUnauthorized] = "OpenAIがAPIキーを拒否しました。キーが正しく有効か確認してください。",
        [TextKey.OpenAIRateLimited] = "OpenAIのレート制限または利用上限に達しました。請求設定や利用制限を確認するか、後でもう一度お試しください。",
        [TextKey.OpenAITemporaryFailure] = "OpenAIが一時的に利用できません。しばらくしてからもう一度お試しください。",
        [TextKey.Save] = "保存",
        [TextKey.Close] = "閉じる",
        [TextKey.SettingsError] = "設定エラー",
        [TextKey.PressModifierAndCharacter] = "修飾キーと文字キーを押してください",
        [TextKey.ShortcutConflictsWithWindows] = "このショートカットはWindowsまたは他のアプリでよく使用されます。別のショートカットを選んでください。",
        [TextKey.ShortcutNeedsMoreModifiers] = "グローバルショートカットにはControl+Altのように修飾キーを2つ以上使用してください。",
        [TextKey.UnsupportedKey] = "対応していないキーです。",
        [TextKey.Translating] = "翻訳中...",
        [TextKey.APIKeyMissing] = "OpenAI APIキーがありません。設定を開いてAPIキーを入力してください。",
        [TextKey.ClipboardTextMissing] = "選択されたテキストが見つかりませんでした。他のアプリでテキストを選択してからR2Transのホットキーを押してください。",
        [TextKey.InvalidHotkey] = "無効なホットキーです",
        [TextKey.ResponseMissing] = "OpenAIの応答に翻訳テキストが含まれていませんでした。",
        [TextKey.AlreadyTranslating] = "翻訳はすでに実行中です。",
        [TextKey.MicrophonePermissionDenied] = "ライブ通訳にはマイクの権限が必要です。",
        [TextKey.MicrophoneUnavailable] = "マイクを開始できませんでした。",
        [TextKey.SystemAudioUnavailable] = "システム音声キャプチャを開始できませんでした。Windowsのプライバシー設定と音声デバイスを確認してから再試行してください。",
        [TextKey.MicrophoneInput] = "マイクのみ",
        [TextKey.SystemAudioInput] = "システム音声のみ",
        [TextKey.MicrophoneAndSystemAudioInput] = "マイク + システム音声",
        [TextKey.LiveInterpreter] = "ライブ通訳...",
        [TextKey.LiveInterpreterTitle] = "ライブ通訳",
        [TextKey.LiveInterpreterConnecting] = "接続中...",
        [TextKey.LiveInterpreterListening] = "リスニング中",
        [TextKey.LiveInterpreterStopped] = "停止中",
        [TextKey.LiveInterpreterError] = "ライブ通訳エラー",
        [TextKey.LiveInterpreterNoSource] = "原文の文字起こしがここに表示されます。",
        [TextKey.LiveInterpreterWaitingSubtitle] = "翻訳字幕がここに表示されます。",
        [TextKey.LiveInterpreterBillingNote] = "リアルタイム翻訳は音声時間に基づいて課金されます。Free tierではgpt-realtime-translateが利用できない場合があります。",
        [TextKey.OpenSettings] = "設定を開く",
        [TextKey.AppRunning] = "R2Transは実行中です",
        [TextKey.TrayHiddenWarning] = "トレイアイコンを非表示にすると、このウィンドウを閉じた時にR2Transが終了します。"
    };

    private static readonly Dictionary<TextKey, string> Chinese = new()
    {
        [TextKey.QuitR2Trans] = "退出 R2Trans",
        [TextKey.Settings] = "设置...",
        [TextKey.Paste] = "粘贴",
        [TextKey.TranslateSelection] = "翻译所选内容",
        [TextKey.TranslationMode] = "翻译模式",
        [TextKey.SettingsTitle] = "R2Trans 设置",
        [TextKey.OpenAIAPIKey] = "OpenAI API 密钥",
        [TextKey.AppLanguage] = "应用语言",
        [TextKey.Hotkey] = "快捷键",
        [TextKey.Model] = "模型",
        [TextKey.AutoDetect] = "自动检测",
        [TextKey.AutoDetectPair] = "自动语言对",
        [TextKey.ConfirmBeforeReplace] = "替换前确认",
        [TextKey.TranslationStyle] = "翻译风格",
        [TextKey.LaunchAtLogin] = "登录时启动",
        [TextKey.ShowTrayIcon] = "显示托盘图标",
        [TextKey.InputSource] = "输入来源",
        [TextKey.AllSystemAudio] = "所有系统音频",
        [TextKey.AudioLevel] = "音频电平",
        [TextKey.MicrophoneLevel] = "麦克风",
        [TextKey.SystemAudioLevel] = "系统",
        [TextKey.KeepInterpreterOnTop] = "置顶",
        [TextKey.SourceTranscript] = "原文转录",
        [TextKey.TranslatedSubtitle] = "翻译",
        [TextKey.SourceLanguage] = "源语言",
        [TextKey.TargetLanguage] = "目标语言",
        [TextKey.CreateAPIKey] = "创建 OpenAI API 密钥",
        [TextKey.OpenAIAPIKeyHelp] = "创建或管理 OpenAI API 密钥",
        [TextKey.WorkMode] = "工作模式",
        [TextKey.MultilingualTranslationMode] = "多语言翻译",
        [TextKey.SameLanguageRewriteMode] = "同语言润色",
        [TextKey.CurrentMode] = "当前模式",
        [TextKey.ConfirmTranslationTitle] = "确认翻译",
        [TextKey.ConfirmTranslationMessage] = "替换所选内容前请检查翻译结果。",
        [TextKey.Replace] = "替换",
        [TextKey.CopyOnly] = "复制",
        [TextKey.Cancel] = "取消",
        [TextKey.Clear] = "清除",
        [TextKey.Ok] = "确定",
        [TextKey.Start] = "开始",
        [TextKey.Stop] = "停止",
        [TextKey.StyleNatural] = "自然",
        [TextKey.StyleFormal] = "正式",
        [TextKey.StylePolite] = "礼貌",
        [TextKey.StyleGroveling] = "过度谦卑",
        [TextKey.StyleNyang] = "喵喵体(仅 ko-KR)",
        [TextKey.NetworkError] = "网络连接失败。请检查互联网连接后重试。",
        [TextKey.OpenAIUnauthorized] = "OpenAI 拒绝了 API 密钥。请检查密钥是否正确且处于启用状态。",
        [TextKey.OpenAIRateLimited] = "已达到 OpenAI 速率限制或配额。请检查账单、使用限制，或稍后重试。",
        [TextKey.OpenAITemporaryFailure] = "OpenAI 暂时不可用。请稍后重试。",
        [TextKey.Save] = "保存",
        [TextKey.Close] = "关闭",
        [TextKey.SettingsError] = "设置错误",
        [TextKey.PressModifierAndCharacter] = "请同时按下修饰键和字符键",
        [TextKey.ShortcutConflictsWithWindows] = "此快捷键常被 Windows 或其他应用使用。请选择其他快捷键。",
        [TextKey.ShortcutNeedsMoreModifiers] = "全局快捷键请使用至少两个修饰键，例如 Control+Alt。",
        [TextKey.UnsupportedKey] = "不支持的按键。",
        [TextKey.Translating] = "正在翻译...",
        [TextKey.APIKeyMissing] = "缺少 OpenAI API 密钥。请打开设置并输入 API 密钥。",
        [TextKey.ClipboardTextMissing] = "未找到所选文本。请在其他应用中选择文本，然后按下 R2Trans 快捷键。",
        [TextKey.InvalidHotkey] = "无效的快捷键",
        [TextKey.ResponseMissing] = "OpenAI 响应中没有包含翻译文本。",
        [TextKey.AlreadyTranslating] = "翻译已在进行中。",
        [TextKey.MicrophonePermissionDenied] = "实时口译需要麦克风权限。",
        [TextKey.MicrophoneUnavailable] = "无法启动麦克风。",
        [TextKey.SystemAudioUnavailable] = "无法启动系统音频捕获。请检查 Windows 隐私/麦克风权限和音频设备，然后重试。",
        [TextKey.MicrophoneInput] = "仅麦克风",
        [TextKey.SystemAudioInput] = "仅系统音频",
        [TextKey.MicrophoneAndSystemAudioInput] = "麦克风 + 系统音频",
        [TextKey.LiveInterpreter] = "实时口译...",
        [TextKey.LiveInterpreterTitle] = "实时口译",
        [TextKey.LiveInterpreterConnecting] = "正在连接...",
        [TextKey.LiveInterpreterListening] = "正在聆听",
        [TextKey.LiveInterpreterStopped] = "已停止",
        [TextKey.LiveInterpreterError] = "实时口译错误",
        [TextKey.LiveInterpreterNoSource] = "源文本转录将显示在这里。",
        [TextKey.LiveInterpreterWaitingSubtitle] = "翻译字幕将显示在这里。",
        [TextKey.LiveInterpreterBillingNote] = "实时翻译按音频时长计费。Free tier 可能不支持 gpt-realtime-translate。",
        [TextKey.OpenSettings] = "打开设置",
        [TextKey.AppRunning] = "R2Trans 正在运行",
        [TextKey.TrayHiddenWarning] = "如果隐藏托盘图标，关闭此窗口会退出 R2Trans。"
    };
}
